apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kargo-demo
  template:
    metadata:
      labels:
        app: kargo-demo
    spec:
      containers:
      - image: 937028213865.dkr.ecr.us-east-1.amazonaws.com/kajabi-base@sha256:2dbe169ee2c7d2b59e880971b664492bb8788d6cec73948fc4ebd9fe6100ac5a
        name: kajabi-base
