apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kargo-demo
  template:
    metadata:
      labels:
        app: kargo-demo
    spec:
      containers:
      - image: 937028213865.dkr.ecr.us-east-1.amazonaws.com/kajabi-base@sha256:af1888f410ba545a8faba28d8c7a89db35829ee3a3cd952c431cb9b5c78e7bda
        name: kajabi-base
