apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kargo-demo
  template:
    metadata:
      labels:
        app: kargo-demo
    spec:
      containers:
      - image: 937028213865.dkr.ecr.us-east-1.amazonaws.com/kajabi-base@sha256:5471811101f367b6752019458423b5d851d197faa47ab1371c45879329114487
        name: kajabi-base
