apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kargo-demo
  template:
    metadata:
      labels:
        app: kargo-demo
    spec:
      containers:
      - image: 937028213865.dkr.ecr.us-east-1.amazonaws.com/kajabi-base@sha256:c6e7d1fd781f64e47b6b8305310304f5fe735d87279bb98422b565f17ac249b8
        name: kajabi-base
